include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat missing required parameters as errors
    missing_required_param: error
    # Dead code
    dead_code: warning

linter:
  rules:
    # Style
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - unnecessary_this

    # Design
    - avoid_classes_with_only_static_members
    - prefer_final_fields
    - prefer_final_locals

    # Performance
    - avoid_function_literals_in_foreach_calls

    # Documentation
    - public_member_api_docs
