import 'package:blade_parser/blade_parser.dart';
import 'package:test/test.dart';

/// Chaos tests with extremely noisy, poorly formatted input.
///
/// These tests simulate real-world "developer chaos":
/// - Code copied from different sources with mixed styles
/// - Refactored code with leftover formatting issues
/// - Templates edited by multiple developers
/// - Code generated by tools with inconsistent output
void main() {
  group('Formatter Chaos Tests', () {
    late BladeFormatter formatter;

    setUp(() {
      formatter = BladeFormatter();
    });

    group('Copy-Paste Chaos', () {
      test('handles code copied from different sources', () {
        // Simulates code copied from different projects with different styles
        const input = '''
<div class="container">
    <h1>Section One</h1>
</div>
<div class='container'>
  <h1>Section Two</h1>
</div>
<div class=container>
<h1>Section Three</h1>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('<div'));
        expect(result, contains('<h1>Section One</h1>'));
        expect(result, contains('<h1>Section Two</h1>'));
        expect(result, contains('<h1>Section Three</h1>'));
      });

      test('handles mixed indentation styles', () {
        const input = '''
<ul>
	<li>Tab indented</li>
    <li>4-space indented</li>
  <li>2-space indented</li>
        <li>8-space indented</li>
</ul>
''';
        final result = formatter.format(input);
        expect(result, contains('<ul>'));
        expect(result, contains('Tab indented'));
        expect(result, contains('4-space indented'));
        // All should be normalized to consistent indentation
        final lines = result.split('\n').where((l) => l.contains('<li>')).toList();
        expect(lines.length, equals(4));
      });

      test('handles mixed quote styles in same element', () {
        const input =
            '''<div class="primary" id='main' data-value=unquoted title="Mixed 'quotes'">Content</div>''';

        final result = formatter.format(input);
        expect(result, contains('class='));
        expect(result, contains('id='));
        expect(result, contains('data-value'));
      });

      test('handles code with Windows and Unix line endings mixed', () {
        const input = '<div>\r\n<p>Windows</p>\n<p>Unix</p>\r\n<p>Mixed</p>\n</div>';

        final result = formatter.format(input);
        expect(result, contains('<p>Windows</p>'));
        expect(result, contains('<p>Unix</p>'));
        expect(result, contains('<p>Mixed</p>'));
        // Should normalize to Unix line endings
        expect(result, isNot(contains('\r')));
      });
    });

    group('Refactoring Leftovers', () {
      test('handles extra blank lines from deleted code', () {
        const input = '''
<div>


<p>Content after deleted section</p>




<p>More content</p>


</div>
''';
        final result = formatter.format(input);
        expect(result, contains('<div>'));
        expect(result, contains('<p>Content after deleted section</p>'));
        expect(result, contains('<p>More content</p>'));
      });

      test('handles orphaned closing directives context', () {
        // Simulates partial refactoring where someone deleted the opening but not the closing
        const input = '''
<div>
@if(\$condition)
<p>Still here</p>
@endif
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('@if(\$condition)'));
        expect(result, contains('@endif'));
      });

      test('handles commented-out alternatives', () {
        const input = '''
<div>
{{-- Old implementation --}}
{{-- <p>{{ \$oldValue }}</p> --}}
<p>{{ \$newValue }}</p>
{{-- Another old thing --}}
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('{{-- Old implementation --}}'));
        expect(result, contains('{{ \$newValue }}'));
      });

      test('handles TODO comments scattered throughout', () {
        const input = '''
<div>
{{-- TODO: Refactor this section --}}
<p>Content</p>
<!-- TODO: Add validation -->
<input type="text">
{{-- FIXME: This breaks on mobile --}}
<button>Submit</button>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('TODO: Refactor'));
        expect(result, contains('TODO: Add validation'));
        expect(result, contains('FIXME:'));
      });
    });

    group('Multi-Developer Chaos', () {
      test('handles different directive spacing preferences', () {
        const input = '''
@if(\$a)
<p>A</p>
@endif
@if(\$b)
<p>B</p>
@endif


@if(\$c)
<p>C</p>
@endif
''';
        final result = formatter.format(input);
        expect(result, contains('@if(\$a)'));
        expect(result, contains('@if(\$b)'));
        expect(result, contains('@if(\$c)'));
      });

      test('handles different attribute ordering styles', () {
        const input = '''
<input type="text" class="form-control" id="field1" name="field1">
<input class="form-control" name="field2" type="text" id="field2">
<input id="field3" type="text" name="field3" class="form-control">
''';
        final result = formatter.format(input);
        expect(result, contains('type="text"'));
        expect(result, contains('class="form-control"'));
        expect(result, contains('id="field1"'));
      });

      test('handles inconsistent component usage', () {
        const input = '''
<x-button>Click me</x-button>
<x-button />
<x-button></x-button>
<x-button type="submit">Submit</x-button>
<x-button
    type="primary"
    size="large"
>
Large Button
</x-button>
''';
        final result = formatter.format(input);
        expect(result, contains('<x-button>Click me</x-button>'));
        expect(result, contains('type="submit"'));
        expect(result, contains('type="primary"'));
      });
    });

    group('Tool-Generated Chaos', () {
      test('handles minified-style inline HTML', () {
        const input =
            '<div><p>One</p><p>Two</p><p>Three</p><ul><li>A</li><li>B</li><li>C</li></ul></div>';

        final result = formatter.format(input);
        expect(result, contains('<p>One</p>'));
        expect(result, contains('<li>A</li>'));
      });

      test('handles over-formatted verbose HTML', () {
        const input = '''
<div
    class="container"
>
    <p
        class="text"
    >
        Content
    </p>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('<div'));
        expect(result, contains('class="container"'));
        expect(result, contains('Content'));
      });

      test('handles generated data attributes', () {
        const input = '''
<div
data-v-1a2b3c4d=""
data-v-5e6f7g8h=""
data-testid="component-12345"
data-cy="test-element"
data-gtm-click="tracking-id"
class="component">
Content
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('data-v-1a2b3c4d'));
        expect(result, contains('data-testid'));
        expect(result, contains('data-cy'));
        expect(result, contains('data-gtm-click'));
      });

      test('handles framework-specific attributes chaos', () {
        const input = '''
<div
x-data="{ open: false }"
x-init="init()"
x-show="open"
x-transition:enter="ease-out duration-300"
x-transition:enter-start="opacity-0"
x-transition:enter-end="opacity-100"
x-transition:leave="ease-in duration-200"
x-transition:leave-start="opacity-100"
x-transition:leave-end="opacity-0"
@click="toggle"
@click.away="close"
@keydown.escape="close"
wire:model="value"
wire:loading.class="opacity-50"
wire:target="save"
class="dropdown">
<p>Dropdown content</p>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('x-data'));
        expect(result, contains('x-transition:enter'));
        expect(result, contains('@click'));
        expect(result, contains('@keydown.escape'));
        expect(result, contains('wire:model'));
        expect(result, contains('wire:loading.class'));
      });
    });

    group('Extreme Whitespace Variations', () {
      test('handles attributes with internal whitespace', () {
        const input = '''
<div class="  spaced   class   names  " data-value="  value  ">Content</div>
''';
        final result = formatter.format(input);
        expect(result, contains('class='));
        expect(result, contains('data-value'));
      });

      test('handles echo with various internal spacing', () {
        const input = '''
<p>{{     \$a     }}</p>
<p>{{ \$b }}</p>
<p>{{\$c}}</p>
<p>{{  \$d  }}</p>
''';
        final result = formatter.format(input);
        // All should be normalized to standard spacing
        expect(result, contains('{{ \$a }}'));
        expect(result, contains('{{ \$b }}'));
        expect(result, contains('{{ \$c }}'));
        expect(result, contains('{{ \$d }}'));
      });

      test('handles directives with various spacing', () {
        const input = '''
@if(\$a)
<p>A</p>
@endif
@if(   \$b   )
<p>B</p>
@endif
@if( \$c )
<p>C</p>
@endif
''';
        final result = formatter.format(input);
        expect(result, contains('@if(\$a)'));
        expect(result, contains('<p>A</p>'));
        expect(result, contains('<p>B</p>'));
        expect(result, contains('<p>C</p>'));
      });

      test('handles text nodes with irregular spacing', () {
        const input = '<p>Word1    Word2\t\tWord3   \t  Word4</p>';

        final result = formatter.format(input);
        expect(result, contains('Word1'));
        expect(result, contains('Word2'));
        expect(result, contains('Word3'));
        expect(result, contains('Word4'));
      });
    });

    group('Complex Nesting Chaos', () {
      test('handles alternating containers and directives', () {
        const input = '''
<div>
@if(\$a)
<section>
@foreach(\$items as \$item)
<article>
@if(\$item->show)
<div>
@can('edit')
<p>{{ \$item }}</p>
@endcan
</div>
@endif
</article>
@endforeach
</section>
@endif
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('<div>'));
        expect(result, contains('@if(\$a)'));
        expect(result, contains('<section>'));
        expect(result, contains('@foreach'));
        expect(result, contains('<article>'));
        expect(result, contains('@can'));
      });

      test('handles components with complex slot nesting', () {
        const input = '''
<x-layout>
<x-slot:header>
<x-nav>
<x-slot:brand>
<img src="/logo.png">
</x-slot>
<x-slot:links>
@foreach(\$links as \$link)
<x-nav-link :href="\$link->url">{{ \$link->label }}</x-nav-link>
@endforeach
</x-slot>
</x-nav>
</x-slot>
<x-slot:content>
<x-card>
<x-slot:header>
<h2>{{ \$title }}</h2>
</x-slot>
<p>{{ \$content }}</p>
</x-card>
</x-slot>
</x-layout>
''';
        final result = formatter.format(input);
        expect(result, contains('<x-layout>'));
        expect(result, contains('<x-slot:header>'));
        expect(result, contains('<x-nav>'));
        expect(result, contains('<x-slot:brand>'));
        expect(result, contains('<x-card>'));
      });

      test('handles conditional component rendering', () {
        const input = '''
@if(\$type === 'card')
<x-card :title="\$title">
{{ \$content }}
</x-card>
@elseif(\$type === 'alert')
<x-alert :type="\$alertType">
{{ \$message }}
</x-alert>
@else
<div class="default">
{{ \$content }}
</div>
@endif
''';
        final result = formatter.format(input);
        expect(result, contains('@if(\$type === \'card\')'));
        expect(result, contains('<x-card'));
        expect(result, contains('@elseif(\$type === \'alert\')'));
        expect(result, contains('<x-alert'));
        expect(result, contains('@else'));
      });
    });

    group('Edge Case Combinations', () {
      test('handles Blade inside Alpine expressions', () {
        const input = '''
<div x-data="{ items: {{ json_encode(\$items) }}, selected: {{ \$defaultSelected }} }">
<template x-for="item in items">
<div x-text="item.name"></div>
</template>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('x-data'));
        expect(result, contains('json_encode'));
        expect(result, contains('<template'));
        expect(result, contains('x-for'));
      });

      test('handles wire:model with Blade conditionals', () {
        // Blade inside attributes is tricky - test standard patterns
        const input = '''
<input
type="text"
wire:model.live="field"
class="{{ \$hasError ? 'error' : '' }}"
>
''';
        final result = formatter.format(input);
        expect(result, contains('wire:model.live'));
        expect(result, contains('class='));
        expect(result, contains('\$hasError'));
      });

      test('handles dynamic component with all attribute types', () {
        const input = '''
<x-dynamic-component
:component="\$componentName"
class="base-class {{ \$extraClass }}"
x-data="{ active: false }"
wire:model="selection"
@click="handle"
data-testid="dynamic-{{ \$id }}"
:disabled="\$isDisabled"
>
<x-slot:header>
{{ \$header }}
</x-slot>
{{ \$content }}
</x-dynamic-component>
''';
        final result = formatter.format(input);
        expect(result, contains('<x-dynamic-component'));
        expect(result, contains(':component'));
        expect(result, contains('x-data'));
        expect(result, contains('wire:model'));
        expect(result, contains('@click'));
        expect(result, contains('data-testid'));
      });

      test('handles escaped content in various contexts', () {
        const input = '''
<div>
<p>Show Vue syntax: @{{ message }}</p>
<p>Email escape: test@@example.com</p>
<p>Blade echo: {{ \$value }}</p>
<p>Raw HTML: {!! \$html !!}</p>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('@{{ message }}'));
        expect(result, contains('@example.com'));
        expect(result, contains('{{ \$value }}'));
        expect(result, contains('{!! \$html !!}'));
      });
    });

    group('Formatting Consistency', () {
      test('produces consistent output regardless of input formatting', () {
        const wellFormatted = '''
<div class="container">
    <p>Content</p>
</div>
''';
        const poorlyFormatted = '''
<div    class="container"  >
        <p  >Content</p  >
   </div>
''';
        const minified = '<div class="container"><p>Content</p></div>';

        final result1 = formatter.format(wellFormatted);
        final result2 = formatter.format(poorlyFormatted);
        final result3 = formatter.format(minified);

        // All should produce similar output structure
        expect(result1, contains('<div class="container">'));
        expect(result2, contains('<div class="container">'));
        expect(result3, contains('<div class="container">'));
      });

      test('maintains idempotency through multiple passes', () {
        const messyInput = '''
<div    class="test"   id="main"  >
     @if(  \$show  )
<p  >{{   \$content   }}</p>
          @endif
    </div>
''';
        final pass1 = formatter.format(messyInput);
        final pass2 = formatter.format(pass1);
        final pass3 = formatter.format(pass2);
        final pass4 = formatter.format(pass3);
        final pass5 = formatter.format(pass4);

        expect(pass1, equals(pass2));
        expect(pass2, equals(pass3));
        expect(pass3, equals(pass4));
        expect(pass4, equals(pass5));
      });

      test('handles progressively messier input', () {
        const level1 = '<div><p>Content</p></div>';
        const level2 = '<div  ><p  >Content</p  ></div>';
        const level3 = '<div    ><p    >Content</p    ></div>';
        const level4 = '<div      ><p      >Content</p      ></div>';

        final r1 = formatter.format(level1);
        final r2 = formatter.format(level2);
        final r3 = formatter.format(level3);
        final r4 = formatter.format(level4);

        // All should produce the same clean output
        expect(r1, equals(r2));
        expect(r2, equals(r3));
        expect(r3, equals(r4));
      });
    });

    group('Attribute Value Chaos', () {
      test('handles URLs with special characters in attributes', () {
        const input = '''
<a href="https://example.com/path?query=value&other=123#section">Link</a>
<img src="https://cdn.example.com/image.jpg?w=100&h=100&format=webp">
<form action="/submit?redirect={{ urlencode(\$url) }}">
</form>
''';
        final result = formatter.format(input);
        expect(result, contains('href="https://example.com'));
        expect(result, contains('src="https://cdn.example.com'));
        expect(result, contains('action="/submit'));
      });

      test('handles JSON in data attributes', () {
        const input = '''
<div
data-config='{"key": "value", "array": [1,2,3]}'
data-options='{"nested": {"deep": true}}'
data-items="{{ json_encode(\$items) }}"
>
Content
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('data-config'));
        expect(result, contains('data-options'));
        expect(result, contains('data-items'));
      });

      test('handles CSS in style attributes', () {
        const input = '''
<div style="color: red; background: url('image.jpg'); font-family: 'Arial', sans-serif;">
<p style="margin: 10px 20px; padding: 5px;">Styled</p>
</div>
''';
        final result = formatter.format(input);
        expect(result, contains('style='));
        expect(result, contains('color:'));
      });

      test('handles event handlers with complex JavaScript', () {
        const input = '''
<button onclick="handleClick(event, { id: 1 }); return false;">Click</button>
<div onmouseover="this.style.backgroundColor='blue'">Hover</div>
<form onsubmit="return validateForm(this)">
<input type="submit">
</form>
''';
        final result = formatter.format(input);
        expect(result, contains('onclick='));
        expect(result, contains('onmouseover='));
        expect(result, contains('onsubmit='));
      });
    });

    group('Special Content Preservation', () {
      test('preserves preformatted content', () {
        const input = '''
<pre>
function example() {
    if (true) {
        return "indented";
    }
}
</pre>
''';
        final result = formatter.format(input);
        expect(result, contains('<pre>'));
        expect(result, contains('</pre>'));
      });

      test('preserves script content', () {
        const input = '''
<script>
const config = {{ \$jsonConfig }};
document.addEventListener('DOMContentLoaded', () => {
    init(config);
});
</script>
''';
        final result = formatter.format(input);
        expect(result, contains('<script>'));
        expect(result, contains('{{ \$jsonConfig }}'));
        expect(result, contains('</script>'));
      });

      test('preserves style content', () {
        const input = '''
<style>
.dynamic-color {
    color: {{ \$primaryColor }};
    background: {{ \$bgColor }};
}
@media (min-width: 768px) {
    .container { max-width: 720px; }
}
</style>
''';
        final result = formatter.format(input);
        expect(result, contains('<style>'));
        expect(result, contains('{{ \$primaryColor }}'));
        expect(result, contains('@media'));
        expect(result, contains('</style>'));
      });

      test('preserves textarea content', () {
        const input = '''
<textarea name="content">
{{ \$existingContent }}

This content has
  multiple lines
    and various
      indentation
</textarea>
''';
        final result = formatter.format(input);
        expect(result, contains('<textarea'));
        expect(result, contains('</textarea>'));
      });
    });
  });
}
