name: blade_playground
description: Interactive web playground for testing the Blade parser
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  blade_parser:
    path: ../../
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/examples/
